spring.application.name=Campus-Connect

spring.datasource.url=jdbc:mysql://localhost:3306/campusconnect
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=23#@#_@#@$FD@_@#D#D_#VRT&_f4uefyh3i
jwt.expiration=86400000