spring.application.name=Campus-Connect

# database connection

spring.datasource.url=jdbc:mysql://localhost:3306/campusconnect
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# JWT setup

jwt.secret=dGhpc0lzQVN1cGVyU2VjdXJlSldUU2VjcmV0S2V5MTIzNDU2Nzg5MA==
jwt.expiration=86400000

# debugging

logging.level.org.springframework.security=DEBUG

# cloudinary setup

cloudinary.cloud-name=${CLOUDINARY_CLOUD_NAME}
cloudinary.api-key=${CLOUDINARY_API_KEY}
cloudinary.api-secret=${CLOUDINARY_API_SECRET}